### PR TITLE
Switch to immutables strict builder

### LINKED ISSUE #118: .addAllClusterWaits overwrites previous waits.
```
ClusterWait a,b,c,d;
DockerComposeRule.builder()
  .addClusterWait(a)
  .addAllClusterWaits(ImmutableList.of(b,c,d)
```

Removes cluster wait 'a' from the list of waits. Things then fail in a very non transparent manner.

### PR DESCRIPTION
**Pull request by iamdanfox**
This removes a few generated methods too, e.g, you can no longer initialise a builder `from` an existing instance.

fixes #118

### CODE REVIEW

**Comment by iamdanfox** [comment]
@jamesneale does this look OK to you?  This guarantees that there's no way to overwrite any previously set builder fields and adds a nicer convenience method to add more `clusterWaits`

File: src/test/java/com/palantir/docker/compose/DockerComposeRuleShould.java [hunk 1]
```diff
@@ -265,6 +277,32 @@ public void when_remove_conflicting_containers_on_startup_is_set_to_false_before
...
+                mock(ClusterWait.class),
+                mock(ClusterWait.class));
+        Collection<ClusterWait> secondAssignment = ImmutableList.of(mock(ClusterWait.class));
+
+        DockerComposeRule twoAssignments = defaultBuilder()
+                .clusterWaits(originalAssignment)
+                .clusterWaits(secondAssignment)
+                .build();
+
+        assertThat(twoAssignments.clusterWaits(), hasSize(3));
```
Comment (jamesneale) [inline src/test/java/com/palantir/docker/compose/DockerComposeRuleShould.java]: Although in theory 3 is sufficient we should probably test what the test says we are xD

File: src/main/java/com/palantir/docker/compose/DockerComposeRule.java [hunk 2]
```diff
@@ -43,7 +43,7 @@
 import org.slf4j.LoggerFactory;
 
 @Value.Immutable
-@Depluralized
+@CustomImmutablesStyle
```
Comment (jamesneale) [inline src/main/java/com/palantir/docker/compose/DockerComposeRule.java]: This is mega although name could probably be better

**Comment by jamesneale** [comment]
LGTM some minor nits but happy to be disagreed with

File: src/test/java/com/palantir/docker/compose/DockerComposeRuleShould.java [hunk 3]
```diff
@@ -224,9 +231,14 @@ public void be_able_to_save_logs_to_a_directory_while_containers_are_running()
 
     @Test
     public void not_shut_down_when_skipShutdown_is_true() throws InterruptedException {
-        defaultBuilder().skipShutdown(true)
-                        .build()
-                        .after();
+        DockerComposeRule.builder()
```
Comment (iamdanfox) [inline src/test/java/com/palantir/docker/compose/DockerComposeRuleShould.java]: `skipShutdown` only takes a boolean, but we are setting `shutdownStrategy` a bit unnecessarily.  Have scoped it down to the one test method that needs it.

File: src/main/java/com/palantir/docker/compose/DockerComposeRule.java (hunk 2 above)
Comment (iamdanfox) [inline src/main/java/com/palantir/docker/compose/DockerComposeRule.java]: Any suggestions?
