### PR TITLE
LocalBuilder: Allow additionalEnvironment to override systemEnvironment

### LINKED ISSUE #131: DockerMachine fails if "system" and "additional" environment variables are duplicated.
Relevant [code](https://github.com/palantir/docker-compose-rule/blob/master/src/main/java/com/palantir/docker/compose/connection/DockerMachine.java#L100):
```
            Map<String, String> environment = ImmutableMap.<String, String>builder()
                    .putAll(systemEnvironment)
                    .putAll(additionalEnvironment)
                    .build();
```

If you set FOO=bar in the "additional environment", but FOO=bar happens to also be set on the system, this will fail.

Options:
1 - merge the entries, fail if there's a conflict (e.g. FOO=bar, FOO=baz -> fail)
2 - merge the entries, choose additional if there's a conflict (e.g. system FOO=bar, add. FOO=baz -> FOO=baz).

### PR DESCRIPTION
**Pull request by gsheasby**
The docker reserved variables (DOCKER_TLS_VERIFY, DOCKER_HOST,
DOCKER_CERT_PATH) are still not allowed in additionalEnvironment.
But the user can now override their own environment variables
programatically. (See AtlasDB PR 1237).

Fixes #131.

### CODE REVIEW

File: src/main/java/com/palantir/docker/compose/connection/DockerMachine.java [hunk 1]
```diff
@@ -100,9 +101,11 @@ public LocalBuilder withEnvironment(Map<String, String> newEnvironment) {
         public DockerMachine build() {
             dockerType.validateEnvironmentVariables(systemEnvironment);
             AdditionalEnvironmentValidator.validate(additionalEnvironment);
+            Map<String, String> combinedEnvironment = Maps.newHashMap();
+            combinedEnvironment.putAll(systemEnvironment);
+            combinedEnvironment.putAll(additionalEnvironment);
             Map<String, String> environment = ImmutableMap.<String, String>builder()
-                    .putAll(systemEnvironment)
-                    .putAll(additionalEnvironment)
+                    .putAll(combinedEnvironment)
```
Comment (felixdesouza) [inline src/main/java/com/palantir/docker/compose/connection/DockerMachine.java]: The two maps seem redundant/verbose. I propose you either return the `combinedEnvironment` or do `ImmutableMap.copyOf(combinedEnvironment)`.
